import Papa from 'papaparse';

/**
 * Raw row structure from the Google Sheet.
 * Headers are auto-generated by PapaParse since the sheet has no proper header row.
 */
export interface RawRow {
  '': string; // Column 0: codice
  _1: string; // Column 1: Nome
  _2: string; // Column 2: Vaso
  _3: string; // Column 3: € al pezzo
  _4: string; // Column 4: € al cc
  _5: string; // Column 5: N.x cassa
  _6: string; // Column 6: N. x piano
  _7: string; // Column 7: Da giardino
  _8: string; // Column 8: Da garden
  _9: string; // Column 9: Foto (sempre vuoto)
  _10: string; // Column 10: Note
  [key: string]: string | undefined;
}

/**
 * Processed product with friendly field names.
 */
export interface Product {
  code: string;
  name: string;
  potSize?: string;
  pricePerPiece?: string;
  pricePerBox?: string;
  numPerBox?: string;
  numPerPlane?: string;
  daGiardino?: string;
  daGarden?: string;
  photo?: string;
  note?: string;
  image: string;
  raw: Record<string, string | undefined>;
}

/**
 * Column name mapping: original CSV header -> technical field name.
 * Customize this to change the internal field names.
 */
const COLUMN_NAMES: Record<string, string> = {
  '': 'code',
  _1: 'name',
  _2: 'potSize',
  _3: 'pricePerPiece',
  _4: 'pricePerBox',
  _5: 'numPerBox',
  _6: 'numPerPlane',
  _7: 'daGiardino',
  _8: 'daGarden',
  _9: 'photo',
  _10: 'note',
};

/**
 * Display labels for fields shown in the modal.
 * Maps technical field names to human-readable labels.
 */
export const FIELD_LABELS: Record<string, string> = {
  code: 'Codice',
  name: 'Nome',
  potSize: 'Vaso',
  pricePerPiece: '€ al pezzo',
  pricePerBox: '€ al cc',
  numPerBox: 'N. per cassa',
  numPerPlane: 'N. per piano',
  daGiardino: 'Da giardino',
  daGarden: 'Da garden',
  photo: 'Foto',
  note: 'Note',
};

/**
 * Remap raw row keys to friendly names.
 */
function remapKeys(row: RawRow): Record<string, string | undefined> {
  const remapped: Record<string, string | undefined> = {};
  for (const [key, value] of Object.entries(row)) {
    const newKey = COLUMN_NAMES[key] || key;
    remapped[newKey] = value;
  }
  return remapped;
}

/**
 * Fetch and parse products from a Google Sheet.
 * @param sheetId - The Google Sheet ID
 * @param baseUrl - Base URL for image paths (e.g., import.meta.env.BASE_URL)
 * @returns Array of processed Product objects
 */
export async function fetchProducts(
  sheetId: string,
  baseUrl: string,
): Promise<Product[]> {
  const sheetUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/export?format=csv`;

  try {
    const response = await fetch(sheetUrl);
    const csvText = await response.text();

    console.log('--- CSV RAW (prime 500 chars) ---');
    console.log(csvText.slice(0, 500));

    const parseResult = Papa.parse<RawRow>(csvText, {
      header: true,
      skipEmptyLines: true,
    });

    console.log('--- HEADERS RILEVATI ---');
    console.log(parseResult.meta.fields);

    console.log('--- PRIMA RIGA DATI (raw) ---');
    console.log(parseResult.data[0]);

    console.log('--- SECONDA RIGA DATI (raw) ---');
    console.log(parseResult.data[1]);

    const products = parseResult.data
      .slice(1) // Skip the first row (header row in the data)
      .filter((row) => row['']?.trim() && row._1?.trim()) // Keep only rows with Code AND Name
      .map((row) => ({
        code: row[''].trim(),
        name: row._1?.trim() || '',
        potSize: row._2?.trim() || undefined,
        pricePerPiece: row._3?.trim() || undefined,
        pricePerBox: row._4?.trim() || undefined,
        numPerBox: row._5?.trim() || undefined,
        numPerPlane: row._6?.trim() || undefined,
        daGiardino: row._7?.trim() || undefined,
        daGarden: row._8?.trim() || undefined,
        photo: row._9?.trim() || undefined,
        note: row._10?.trim() || undefined,
        image: `${baseUrl}/images/${row[''].trim()}.jpeg`,
        raw: remapKeys(row),
      }))
      .slice(1);

    console.log('--- PRIMO PRODOTTO PROCESSATO ---');
    console.log(products[0]);

    console.log(`--- TOTALE PRODOTTI: ${products.length} ---`);

    return products;
  } catch (error) {
    console.error('Failed to fetch or parse product data:', error);
    return [];
  }
}
