import Papa from 'papaparse';

/**
 * Raw row structure from the Google Sheet.
 * Headers are auto-generated by PapaParse since the sheet has no proper header row.
 */
export interface RawRow {
  '': string; // Column 0: Code
  _1: string; // Column 1: Name
  _2: string; // Column 2: Format/Size
  _3: string; // Column 3: Price
  _4: string; // Column 4: Note
  [key: string]: string | undefined; // Additional columns
}

/**
 * Processed product with friendly field names.
 */
export interface Product {
  code: string;
  name: string;
  price: string;
  note?: string;
  image: string;
  dimension?: string;
  numPack?: string;
  numPlane?: string;
  daGiardino?: string;
  daGarden?: string;
  raw: Record<string, string | undefined>;
}

/**
 * Column name mapping: original CSV header -> technical field name.
 * Customize this to change the internal field names.
 */
const COLUMN_NAMES: Record<string, string> = {
  '': 'code',
  _1: 'name',
  _2: 'dimension',
  _3: 'price',
  _4: 'note',
  _5: 'num_pack',
  _6: 'num_plane',
  _7: 'col_7',
  _8: 'col_8',
  _9: 'col_9',
  _10: 'col_10',
};

/**
 * Display labels for fields shown in the modal.
 * Maps technical field names to human-readable labels.
 */
export const FIELD_LABELS: Record<string, string> = {
  code: 'Codice',
  name: 'Nome',
  dimension: 'Dimensione vaso in cm',
  price: 'Prezzo',
  note: 'Note',
  num_pack: 'Numero per cassa',
  num_plane: 'Numero per piano',
  col_7: 'Da giardino',
  col_8: 'Da garden',
  col_9: 'col_9',
  col_10: 'col_10',
};

/**
 * Remap raw row keys to friendly names.
 */
function remapKeys(row: RawRow): Record<string, string | undefined> {
  const remapped: Record<string, string | undefined> = {};
  for (const [key, value] of Object.entries(row)) {
    const newKey = COLUMN_NAMES[key] || key;
    remapped[newKey] = value;
  }
  return remapped;
}

/**
 * Fetch and parse products from a Google Sheet.
 * @param sheetId - The Google Sheet ID
 * @param baseUrl - Base URL for image paths (e.g., import.meta.env.BASE_URL)
 * @returns Array of processed Product objects
 */
export async function fetchProducts(
  sheetId: string,
  baseUrl: string,
): Promise<Product[]> {
  const sheetUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/export?format=csv`;

  try {
    const response = await fetch(sheetUrl);
    const csvText = await response.text();

    const parseResult = Papa.parse<RawRow>(csvText, {
      header: true,
      skipEmptyLines: true,
    });

    const products = parseResult.data
      .slice(1) // Skip the first row (header row in the data)
      .filter((row) => row['']?.trim() && row._1?.trim()) // Keep only rows with Code AND Name
      .map((row) => ({
        code: row[''].trim(),
        name: row._1?.trim() || '',
        price: row._3?.trim() || '',
        note: row._4?.trim() || undefined,
        image: `${baseUrl}/images/${row[''].trim()}.jpeg`,
        dimension: row._2?.trim() || undefined,
        numPack: row._5?.trim() || undefined,
        numPlane: row._6?.trim() || undefined,
        daGiardino: row._7?.trim() || undefined,
        daGarden: row._8?.trim() || undefined,
        raw: remapKeys(row),
      }))
      .slice(1);

    return products;
  } catch (error) {
    console.error('Failed to fetch or parse product data:', error);
    return [];
  }
}
